use crate::meta::PROBLEMS;

PROBLEMS! {
    01 => NO_TIME_FOR_A_TAXICAB,
    02 => BATHROOM_SECURITY,
    03 => SQUARES_WITH_THREE_SIDES,
    04 => SECURITY_THROUGH_OBSCURITY,
    05 => HOW_ABOUT_A_NICE_GAME_OF_CHESS,
    06 => SIGNALS_AND_NOISE
}
