use aoc_meta::PROBLEMS;

PROBLEMS! {
    01 => NO_TIME_FOR_A_TAXICAB,
    02 => BATHROOM_SECURITY,
    03 => SQUARES_WITH_THREE_SIDES,
    04 => SECURITY_THROUGH_OBSCURITY,
    05 => HOW_ABOUT_A_NICE_GAME_OF_CHESS,
    06 => SIGNALS_AND_NOISE,
    07 => INTERNET_PROTOCOL_VERSION_7,
    08 => TWO_FACTOR_AUTHENTICATION,
    09 => EXPLOSIVES_IN_CYBERSPACE,
    10 => BALANCE_BOTS,
    11 => RADIOISOTOPE_THERMOELECTRIC_GENERATORS,
    12 => LEONARDOS_MONORAIL,
    13 => A_MAZE_OF_TWISTY_LITTLE_CUBICLES,
    14 => ONE_TIME_PAD,
    15 => TIMING_IS_EVERYTHING,
    16 => DRAGON_CHECKSUM,
    17 => TWO_STEPS_FORWARD,
}
