use aoc_meta::PROBLEMS;

PROBLEMS! {
    01 => SECRET_ENTRANCE,
    02 => GIFT_SHOP,
    03 => LOBBY,
    04 => PRINTING_DEPARTMENT,
    05 => CAFETERIA,
    06 => TRASH_COMPACTOR,
    07 => LABORATORIES,
    08 => PLAYGROUND,
}
