name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: cargo-bins/cargo-binstall@v1.10.5
      - run: cargo binstall cargo-nextest --secure --no-confirm
      - run: cargo nextest run --release --verbose
