name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install `cargo-binstall`
        uses: cargo-bins/cargo-binstall@v1.10.5
      - name: Install `cargo-nextest`
        run: cargo binstall cargo-nextest --secure --no-confirm
      - name: Build
        run: cargo build --release --verbose
      - name: Test
        run: cargo nextest run --release --verbose --no-fail-fast
    env:
      INPUT_2015_1: ${{ secrets.INPUT_2015_1 }}
      INPUT_2015_2: ${{ secrets.INPUT_2015_2 }}
      INPUT_2015_3: ${{ secrets.INPUT_2015_3 }}
      INPUT_2015_4: ${{ secrets.INPUT_2015_4 }}
      INPUT_2015_5: ${{ secrets.INPUT_2015_5 }}
      INPUT_2015_6: ${{ secrets.INPUT_2015_6 }}
      INPUT_2015_7: ${{ secrets.INPUT_2015_7 }}
      INPUT_2015_8: ${{ secrets.INPUT_2015_8 }}
      INPUT_2015_9: ${{ secrets.INPUT_2015_9 }}
