name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test Solutions
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: -C target-cpu=native

    steps:
      - uses: actions/checkout@v4
      - name: Install `cargo-binstall`
        uses: cargo-bins/cargo-binstall@v1.10.5
      - name: Install `nextest`, `rage`, `just`
        run: cargo binstall cargo-nextest rage just --secure --no-confirm
      - name: Test
        run: just test
        env:
          AOC_INPUTS_PUBKEY: ${{ secrets.AOC_INPUTS_PUBKEY }}
          AOC_INPUTS_SECRET: ${{ secrets.AOC_INPUTS_SECRET }}
