name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test AoC Solutions
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install `cargo-binstall`
        uses: cargo-bins/cargo-binstall@v1.10.5
      - name: Install `cargo-nextest`
        run: cargo binstall cargo-nextest --secure --no-confirm
      - name: Build
        run: cargo build --release --verbose
      - name: Test
        run: cargo nextest run --release --verbose --no-fail-fast
        env:
          INPUT_2015_01: ${{ secrets.INPUT_2015_01 }}
          INPUT_2015_02: ${{ secrets.INPUT_2015_02 }}
          INPUT_2015_03: ${{ secrets.INPUT_2015_03 }}
          INPUT_2015_04: ${{ secrets.INPUT_2015_04 }}
          INPUT_2015_05: ${{ secrets.INPUT_2015_05 }}
          INPUT_2015_06: ${{ secrets.INPUT_2015_06 }}
          INPUT_2015_07: ${{ secrets.INPUT_2015_07 }}
          INPUT_2015_08: ${{ secrets.INPUT_2015_08 }}
          INPUT_2015_09: ${{ secrets.INPUT_2015_09 }}
          INPUT_2015_10: ${{ secrets.INPUT_2015_10 }}
          INPUT_2015_11: ${{ secrets.INPUT_2015_11 }}
          INPUT_2015_12: ${{ secrets.INPUT_2015_12 }}
          INPUT_2015_13: ${{ secrets.INPUT_2015_13 }}
          INPUT_2015_14: ${{ secrets.INPUT_2015_14 }}
          INPUT_2015_15: ${{ secrets.INPUT_2015_15 }}
          INPUT_2015_16: ${{ secrets.INPUT_2015_16 }}
          INPUT_2015_17: ${{ secrets.INPUT_2015_17 }}
